application:
  security:
    jwt:
      secret-key: 4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a
      expiration: 36000000 # 10 hours
      refresh-token:
        expiration: 252000000 # 7 days

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/battle_code
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug
    org.springframework.cors: debug
    org.springframework.security.web.csrf: trace